### PR TITLE
docs: update component health stats

### PR DESCRIPTION
**Pull request by mcwinter07**
## Why
Updating component health stats based on changes in past 2 weeks

## What
- update docs for datepicker to add story link
- update loading skeleton health stats

### CODE REVIEW

**Review by HeartSquared — DISMISSED** [review]

**Review by christian314159 — APPROVED** [review]

**Comment by dougmacknz** [comment]
@christian314159 might hate me for this but there's some things that need to go to false:
```
Slider -> all variants
Likert Scale -> latest design
Inline notification -> all variants
```

**Comment by HeartSquared** [comment]
Oof, if we're going to go backwards, might want to make Select's UI parity (latestDesign) `false` too 😅

**Comment by dougmacknz** [comment]
Is there a part of Select that isn't matching? I'm aware of the missing variants + the variant that needs to be deleted, but wasn't aware of any latest design issues.

**Comment by HeartSquared** [comment]
>Is there a part of Select that isn't matching? I'm aware of the missing variants + the variant that needs to be deleted, but wasn't aware of any latest design issues.

Even if you count the reversed styles as variants as opposed to parity, it's actually missing the focus state styles and there's some spacing issues between the label + element as well as on the multiselect between the box and the pills.

**Review by christian314159 — APPROVED** [review]

**Pull request merged**
