### PR TITLE
feat: Add strong selector for bold paragraph text

### PR DESCRIPTION
**Pull request by sebpearce**
# Objective

Adds a rule for nested `strong` elements inside Paragraph components to give them the correct font weight.

# Motivation and Context

Addresses part of #1011.

Using `<strong>` is a standard way of implementing bold text, and is more flexible than creating a bold variant for the Paragraph component.

⚠️  This will potentially cause visual changes if people have already used `<strong>` tags inside a Paragraph component. If they have done that, they will currently be seeing the incorrect font weight (700) instead of the correct one (600) unless they have written a similar nested rule in their own code (it's a no-no for consumers to reach into Kaizen components this way, but possible).

# Checklist

- [ ] If this contains visual changes, has it been reviewed by a designer?
- [ ] If this introduces either a new component or a breaking change to an existing component, has it been reviewed by an advocate? (Ask in #prod_design_systems)
- [ ] I have considered likely risks of these changes and got someone else to QA as appropriate
- [x] I have or will communicate these changes to the front end practice

### CODE REVIEW

**Review by mbylstra — APPROVED** [review]
Interesting one whether this is feat or breaking! My gut feeling was to make it a breaking change (erring more on the side of breaking than feat when in doubt), but thinking it through some more it's really hard to imagine a scenario where this could make things any worse or be contraversional, so it doesn't seem worth "freaking people out" by a breaking change.

(even though my interpretation of "breaking change" is more like "user facing change" rather than breaking in the sense of something being _broken_ or the potential for something breaking)

Long term I'm not sure whether we should _encourage_ people to use html tags directly rather than use a component. My thought process is that it makes it more possible to target completely different platforms (like native mobile) in the future with the same components, but that is very hypothetical and probably not worth overthinking (and we don't even have a way to do strong/bold with components at the moment anyway)

**Comment by sebpearce** [comment]
Cheers 👍 

Re: encouraging tags, it has come up a few times that using tags for both 1) links and 2) strong/emphasis styles allows consumers to have more flexibility in terms of dynamically rendering content inside a component. I guess we can start a thread or issue on this to flesh it out if we need though.

**Review by jasononeil — APPROVED** [review]
I don't view this as a breaking change. I'm personally in favour of using `<strong>` as is. Would defer to @allybeaton for a tech lead decision though :)

**Comment by sebpearce** [comment]
Going to merge this as I think it's pretty safe.

**Pull request merged**
