### PR TITLE
docs: Improve visibility of deprecated components

### PR DESCRIPTION
**Pull request by ActuallyACat**
# About
The deprecated components in Kaizen are now a little more explicit. I have: 
* Moved `menu-list` to legacy-packages. 
* Added a large `# Deprecated` warning within the stories of all deprecated components (React only - the Storybook addon doesn't work for Elm). Elm consumers will need to refer to the story name in storybook. 
* Deprecated `menu-list` and `title-block`  with `npm deprecate`. see here: 
Screen Shot 2020-09-01 at 11 13 41 am. This will also appear on the CLI when you install `@kaizen/draft-menu-list`.
* Added type hints for deprecated props and components.

## Questions 
What have I missed? 
Are there more deprecated components / props? 
Have I accidentally flagged something that's not deprecated?

## Not included 
Warnings when a deprecated component is mounted. I'd like to experiment with how noisy it makes CLI - I will handle this in a separate PR.

References https://github.com/cultureamp/kaizen-design-system/issues/701

### CODE REVIEW

**Comment by ActuallyACat** [comment]
@sebpearce @sampnorris Is `@kaizen/draft-title-block` deprecated?

**Comment by sebpearce** [comment]
@ActuallyACat Practically yes, but technically it will be in a couple of weeks once the Zen one has been rolled out everywhere. I think it's fine to add it to the list here 👍

**Comment by sebpearce** [comment]
Just had a look through this and at the branch preview – great stuff 👌 

I realised I missed the Elm Text component `deprecated` label when I added them a few weeks ago 🤦  
image
Any chance we could piggyback that on this PR?

**Comment by ActuallyACat** [comment]
Good catch @sebpearce - I've updated this now.

**Comment by dougmacknz** [comment]
Is `NavigationBar` deprecated in favour of `ZenNavigationBar`?

Off topic from this PR, but we've got two different conventions for where to put `Zen`, for `TitleBlock` we've done a suffix `TitleBlockZen`, and for `NavigationBar` we've done a prefix `ZenNavigationBar`. I would vote for the former, so that they sit side by side, and it's easy to see that it's a replacement.

**Review by dougmacknz — APPROVED** [review]
Otherwise, everything here is looking good to me. We could do a follow up PR for the `NavigationBar` if we wanted. This will definitely help us avoid using deprecated components, thank you :)

**Comment by ActuallyACat** [comment]
> I would vote for the former 
+++ for the reasons you mentioned - it's much better for visibility. Not sure what that's going to mean for the existing component though 🤔

**Pull request merged**
