### PR TITLE
feat: handle long text multiline or truncated

### PR DESCRIPTION
**Pull request by NatalieLoyzaga**
## Why

to fit text within the button and not compromise on a11y

## What

- Truncate the button value always 
- Allow long paragraph options to go on multiline
- If long single word option - do not word-break and allow horizontal scroll

**Button Value**

image

**Dropdown**

image

image

### CODE REVIEW

**Comment by gyfchong** [comment]
Should the chevron stay aligned to the top? :D

**Comment by gyfchong** [comment]
I'm a bit on the fence about showing the dropdown variations separated from the select, technically they should belong to the not-yet-built popover component.

Is it possible to have the select default open to show them?

**Review by gyfchong — APPROVED** [review]

**Comment by gyfchong** [comment]
I don't see the focus ring anymore...?
image

**Comment by NatalieLoyzaga** [comment]
@gyfchong Buildkite is still building so the dev link is old eeek sorry I was to prompt to ping you

**Review by gyfchong — APPROVED** [review]
Good stuff!

**Pull request merged**
