### PR TITLE
feat: Slider component

### PR DESCRIPTION
**Pull request by ellisjas**
# Objective

Copy over slider from performance, located in `performance-ui/src/entry/OneOnOneSpacePage/CheckIn/RatingScale.tsx`

# Motivation and Context 

This component is needed for activities in Skills coach.

# Screenshots (if appropriate)
Screen Shot 2021-01-25 at 1 05 38 pm

# Checklist

- [ ] If this contains visual changes, has it been reviewed by a designer? 
- [ ] I have considered likely risks of these changes and got someone else to QA as appropriate
- [x] I have or will communicate these changes to the front end practice

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline? 
- Have Storybook stories been updated? 

**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask Design Systems team to review it to catch any issues.

### CODE REVIEW

**Review by kemblesong — APPROVED** [review]
LGTM

**Comment by kemblesong** [comment]
Could be worth updating the component's README to list anything you feel is missing (RTL support?)

**Comment by ellisjas** [comment]
> Could be worth updating the component's README to list anything you feel is missing (RTL support?)

It has RTL support :)

**Comment by ellisjas** [comment]
[Slider bar scale component](https://trello.com/c/4jT1MewV/320-slider-bar-scale-component)

**Pull request merged**
