### PR TITLE
feat: Delete drafts from core kaizen

### PR DESCRIPTION
**Pull request by ActuallyACat**
Chromatic build: https://www.chromatic.com/build?appId=5e12c297b9d9020020789ca3&number=159

Branch to fix up errors in Perf-ui: https://github.com/cultureamp/performance-ui/compare/ally/update-kaizen?expand=1

Draft PR for murmur: https://github.com/cultureamp/murmur/pull/13019

### CODE REVIEW

**Comment by sebpearce** [comment]
LGTM. Any idea what happened with the Table, Layout & InlineNotification? Were they just stragglers that slipped through somehow?

**Comment by ActuallyACat** [comment]
> LGTM. Any idea what happened with the Table, Layout & InlineNotification? Were they just stragglers that slipped through somehow?
I don't think they were picked up by the sweep since the stories are in ` packages/component-library/stories/` not ` draft-packages/stories/`. 

Though now i'm looking at it.... Those table stories need to move.

**Comment by mbylstra** [comment]
I've run the diff script between the new drafts and the old drafts. There were only differences in 
the Elm Select, ZenNavigationBar and ZenOffCanvas. I've confirmed that the changes in the draft packages are newer (nothing needs to be ported across).

**Comment by mbylstra** [comment]
I decided to merge this, so I can bump it in Murmur. Hope that's cool!

**Pull request merged**
