### PR TITLE
docs: add README.md to deprecated-component-library-helpers

### PR DESCRIPTION
**Pull request by mbylstra**

### CODE REVIEW

**Comment by sebpearce** [comment]
I reckon this README could be a good opportunity to put in extra reminders about best practices etc. I'll add something soon.

**Comment by ActuallyACat** [comment]
Can we resurface this now we're in cooldown? Things that (I think) might be good to add to the README: 

```
# About 
deprecated-component-library-helpers contains helpers (scss mixins, utilities, etc) that the Design Systems Team have deprecated, or are planning to deprecate.

# Usage

## Install 
yarn add @kaizen/deprecated-component-library-helpers

## When to use
* When you are adding functionality to an existing Haml file (have you considered refactoring? https://trello.com/c/Vll33o9Q/21-haml-needs-to-go) 
* ???

## When NOT to use 
* When you have an equivalent Elm or React component you can use instead
* ???
```

**Comment by sebpearce** [comment]
I'll write this up this week 👍

**Comment by didoesdigital** [comment]
Let's link this and other relevant package READMEs from the main Kaizen Design System README, especially design tokens.

**Pull request merged**
