### PR TITLE
chore: add preflight to tailwind config

### PR DESCRIPTION
**Pull request by mcwinter07**
## Why
validate UI changes against chromatic and test Tailwind Preflight

## What
- remove flag in tailwind config to disable pre-flight

### CODE REVIEW

**Comment by gyfchong** [comment]
Yeahhh there's a lot of chromatic regression lol...

**Comment by mcwinter07** [comment]
> Yeahhh there's a lot of chromatic regression lol...

@gyfchong think its worth creating a tickets to insulate the styles from these specific components from the preflight or just tackle them in this PR?

**Comment by gyfchong** [comment]
@mcwinter07 I think we're going to have to park this ticket and assess the solution options for insulation. But this was good as an exploration, I'll reply to Jakub's GH discussion outlining our next steps.

**Comment by mcwinter07** [comment]
> @mcwinter07 I think we're going to have to park this ticket and assess the solution options for insulation. But this was good as an exploration, I'll reply to Jakub's GH discussion outlining our next steps.

Cool beans - just as it relates to some of the work I've been doing on updating the FE template tailwind config - I should avoid adding the preflight into that for now then @gyfchong?

**Comment by gyfchong** [comment]
> Cool beans - just as it relates to some of the work I've been doing on updating the FE template tailwind config - I should avoid adding the preflight into that for now then @gyfchong?

Yeah that's correct, let's put a pin on anything related to Preflight support

**Pull request closed without merging**
