### PR TITLE
feat: Allow generic textarea props on TextArea and TextAreaField

### PR DESCRIPTION
**Pull request by dougmacknz**
# Objective
Allows consumers of `TextAreaField` and `TextArea` to send in any generic `textarea` props.

# Motivation and Context 
If you need to add a generic prop to our text area component (such as `maxLength` or any `aria` property`) - we need to go through the process of adding it to the component in Kaizen, then update the package on the consuming repo, which is a time consuming process, and causes code bloat. 

# Checklist
[ ] I have considered likely risks of these changes and got someone else to QA as appropriate
[ ] I have or will communicate these changes to the front end practice

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline? 
- Have Storybook stories been updated? 

**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask Design Systems team to review it to catch any issues.

### CODE REVIEW

**Comment by lijuenc** [comment]
Just copying my comment from Slack in case people want to discuss it here:

> I like the how it extends the native element’s props:
`interface Props extends React.HTMLAttributes<HTMLTextAreaElement>`
To me it makes sense to allow this for those components which are essentially wrapping some native component and making it look/behave nicer

**Comment by makenosound** [comment]
I think this broadly makes sense, and I’m in favour of us adopting this approach. For ease of reference, here’s the interface we’d be allowing:

```
interface TextareaHTMLAttributes<T> extends HTMLAttributes<T> {
    autoComplete?: string;
    autoFocus?: boolean;
    cols?: number;
    dirName?: string;
    disabled?: boolean;
    form?: string;
    maxLength?: number;
    minLength?: number;
    name?: string;
    placeholder?: string;
    readOnly?: boolean;
    required?: boolean;
    rows?: number;
    value?: string | ReadonlyArray<string> | number;
    wrap?: string;

    onChange?: ChangeEventHandler<T>;
}
```

Only thing I’m wondering if if we want to create a new interface that _omits_ specific attributes that don’t make sense for us. We probably don’t want to allow people to use `col` or `row` to size textareas for example, since we’d prefer to control those attributes with CSS.

*****

Also TIL `<textarea form="id_of_form_somewhere_on_page">` 🙃

**Comment by dougmacknz** [comment]
> Only thing I’m wondering if if we want to create a new interface that omits specific attributes that don’t make sense for us. We probably don’t want to allow people to use col or row to size textareas for example, since we’d prefer to control those attributes with CSS.

This component currently encourages the use of `rows`. I recommend that over controlling height with CSS for `textarea`s to avoid having to factor in line height else potentially end up with a height that ends up cutting off text vertically, especially considering inconsistencies across devices.

`cols` on the other hand I wouldn't use, but I wouldn't go out of my way to block its usage.

**Comment by ActuallyACat** [comment]
I'm mostly cool with this. Speaking generally, the issues I see with this approach in the wider system:
* Naming collisions, or naming duplication. E.g. if we called `disabled` attribute something like `isDisabled` we would then have two ways to do the same thing. 
* If it's in the interface there's an implicit expectation for consumers that attribute would work the same way they would expect it to work on a native element. Is this the case? Do we test all these attributes?

**Comment by dougmacknz** [comment]
> Naming collisions, or naming duplication. E.g. if we called disabled attribute something like isDisabled we would then have two ways to do the same thing.

Yeah, we'll want to be weary of not duplicating native behaviour when using this. The consequences shouldn't be too bad, other than needing to do a big sweep of fixing usages if we find a duplicate that's been heavily used.

> If it's in the interface there's an implicit expectation for consumers that attribute would work the same way they would expect it to work on a native element. Is this the case? Do we test all these attributes?

I would imagine we won't be able to test every possible thing and combination of different attributes, so this approach definitely will open us up to potential issues like "I can send `disabled` to this component but it doesn't look right", and I suppose there is a possibility of some native functionality not working due to a conflict with some functionality we have introduced to the component. I'd say this would be a very rare case though. The only case I see where this happens is if you have heavily adjusted functionality on a native element, in which case this pattern probably shouldn't be used.

Another thing to be weary of, in this instance I have allowed `textarea` attributes to be sent to `TextAreaField` which is a wrapper on `TextArea`. So there is an assumption that the props you send with go through to `TextArea` (rather than be applied to the container, or the label, etc). In this case I'd say it still makes sense, but something to keep in mind.

**Comment by makenosound** [comment]
> Yeah, we'll want to be weary of not duplicating native behaviour when using this.

I think we’d want consistency of API as much as possible, but it seems legit to me to overload the native duplicate in some ways potentially for a behaviour like `disabled`. As long as we’re translating the _spirit_ of the native API through to the native element then I think that sort of overloading is fine.

***

Feels like we perhaps first need to decide conceptually what we consider _our_ `<Textarea>` component to be: is it an lightweight wrapper for the native `<textarea>` or is it a component we want to build tighter control aroun?

**Comment by lijuenc** [comment]
>As long as we’re translating the spirit of the native API through to the native element then I think that sort of overloading is fine

wonder if TypeScript's `extends` (or something else) can make it obvious enough that a property on the native element is being overloaded, that way the person implementing it is at least made aware that they are getting close to native behaviour and can avoid drastic changes.

**Review by ActuallyACat — APPROVED** [review]

**Pull request merged**
