### PR TITLE
feat: border styles for likert scale

### PR DESCRIPTION
**Pull request by NatalieLoyzaga**
## Why

 
Fixes https://cultureamp.atlassian.net/jira/software/projects/KDS/boards/289?label=advocate_task&selectedIssue=KDS-294

## What

- Updated border width to 2px (using tokens)
- Updated border colours to be gray-500
-  Removed deprecated styles and replaced with tokens

image

### CODE REVIEW

**Review by Moskvyak — DISMISSED** [review]

**Review by mcwinter07 — COMMENTED** [review]
The border thickness looks good, but the focus styles feel a little off to me - might be worth flagging with @jmitsios to see what the ideal for ring should be since this could be some lingering issues with the scale buttons?

Just looking at the button as an example:
Screen Shot 2022-04-05 at 11 10 39 am
vs the Likert scale
Screen Shot 2022-04-05 at 11 12 19 am

**Comment by jmitsios** [comment]
@NatalieLoyzaga Awesome stuff!   The only thing I noticed also is the label doesn't seem to span the full width of the component, so they're a bit off-center:
image

**Review by mcwinter07 — APPROVED** [review]
Looking flash 🦖 Merge in good health!

**Review by mcwinter07 — APPROVED** [review]
Nice 🦖 merge in good health!

**Pull request merged**
