### PR TITLE
feat: Add data-automation-class to generic notification

### PR DESCRIPTION
**Pull request by okeeffed**
This will add a ` data-automation-class` to each notification with their `type` and `style` to find a generic match as opposed to specific notification matches. 

Reference conversation: https://cultureamp.slack.com/archives/C2ZNME08P/p1597132217066600

Screen Shot 2020-08-12 at 10 52 23 am

### CODE REVIEW

**Comment by mbylstra** [comment]
I just realised that Toasts are notifications,  so that was a bad example, but the point was more that words like "affirmative" and "global" are very generic and might be on other components, making it hard to narrow down to notifications/toasts.

**Comment by mbylstra** [comment]
Oh , I get it now, the type is either "toast" or "notification" - been a while since I looked at this component. Forget what I said. Approved!

**Comment by mbylstra** [comment]
Actually..... I should have looked into this more before speaking.....

it works well for` toast`, but the other variants `global` an `inline` are very generic words. I don't think it'd hurt to put `notification` in there as well: eg `"notification toast cautionary"` and `"notification global cautionary"`

**Comment by okeeffed** [comment]
> Actually..... I should have looked into this more before speaking.....
> 
> it works well for` toast`, but the other variants `global` an `inline` are very generic words. I don't think it'd hurt to put `notification` in there as well: eg `"notification toast cautionary"` and `"notification global cautionary"`

Yeah, easy! I was thinking of having `notification` in there too but I wasn't sure at what point the class names would become superfluous.

**Comment by mbylstra** [comment]
On the one hand they add extra dom weight, but on the other hand I think they are really nice for developers to be able to find out what a component is just by doing inspect element. Sometimes all you see is divs and spans, and obfuscated class names, so it gives you something to search for in a codebase if you're trying to find where something is implemened. I doubt the dom weight is significant.

**Comment by okeeffed** [comment]
Okies @mbylstra I've updated!

> I doubt the dom weight is significant.

I think Frontend Ops were considering removing `data-automation-*` during build down the track based on environment, right? Might not be fun for now, but I think that might happen in the not-so-distant future?

**Comment by mbylstra** [comment]
> I think Frontend Ops were considering removing data-automation-* 
what does this mean exactly? Do you mean replacing with `data-testid`?

**Comment by mbylstra** [comment]
I was thinking about that. Maybe `data-test-class` is a better name for consistency with react testing library  or  `data-testclass` 🙄. I think changing the name of `data-automation-class` is less important than `data-automation-id` as the concept doesn't exist anywhere else as far as I know.

**Comment by okeeffed** [comment]
Oh as in stripping those tags out using Webpack based on environment during the build! So it could still be used for testing, but just wouldn’t be in the client-facing production bundles. Sorry I just saw this on my phone @mbylstra :(

**Comment by mbylstra** [comment]
I could go either way - they add weight to the DOM, but they are also quite useful for debugging, even in production. Eg: you get a support ticket for a page in production, but you can't figure out what part of the code base is generating it or reproducing it locally - you can look at the attrs to help figure out whether it's coming from a Kaizen component or not, which can then help you figure out where the source code is that's generating the page/element. I think being able to debug is more important actually - I doubt that attrs would have much of an impact on page size. I've had to spend hours in the past trying to figure where the hell a div is coming from.

**Pull request merged**
