### PR TITLE
ci: enable corepack in BuildKite docker build step for pnpm

### PR DESCRIPTION
**Pull request by HeartSquared**
## Why

BuildKite can't find pnpm.

## What

Help BuildKite find pnpm.

### CODE REVIEW

**Review by mcwinter07 — APPROVED** [review]
🦖 🐜

**Comment by gyfchong** [comment]
Changeset though

**Comment by HeartSquared** [comment]
> Changeset though

No need. Not touching a package file :)

**Comment by gyfchong** [comment]
Oh does the main branch comparison for changesets not work with `pnpm`?

**Comment by gyfchong** [comment]
> No need. Not touching a package file :)

Oh yeah this is a thing

**Comment by gyfchong** [comment]
Wondering if its just simpler to always require one regardless

**Comment by HeartSquared** [comment]
> Oh does the main branch comparison for changesets not work with `pnpm`?

It does. I forgot where the setting was, but I'm pretty sure it only cares if something in `packages` changes

**Pull request merged**
