### PR TITLE
ci: Fix clean scripts in design-tokens and stylelint-plugin

### PR DESCRIPTION
**Pull request by ActuallyACat**
# Objective
Some build artifacts are not being properly cleaned. I've tidied up the `clean` scripts in design-tokens, component-library and stylelint-plugin, and, have hopefully made them a little easier to reason about. 

Closes https://github.com/cultureamp/kaizen-design-system/issues/1729

# Screenshots (if appropriate)
Screen Shot 2021-06-29 at 9 59 24 am

# Checklist

- [x] If this contains visual changes, has it been reviewed by a designer?
- [x] If this introduces either a new component or a breaking change to an existing component, has it been reviewed by an advocate? (Ask in #prod_design_systems)
- [x] I have considered likely risks of these changes and got someone else to QA as appropriate
- [x] I have or will communicate these changes to the front end practice

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline?
- Have Storybook stories been updated?

### CODE REVIEW

**Review by dougmacknz — APPROVED** [review]
I'll admit I haven't had a good look at this problem, but looks fine.

If I heard you correctly in stand up - this is more of a band-aid solution until we can come up with something more universal?

**Comment by ActuallyACat** [comment]
> If I heard you correctly in stand up - this is more of a band-aid solution until we can come up with something more universal?

Yup, in an ideal world all packages would compile to a consistent `dist` directory instead of compiling in place. I'll write up an issue for this - there's a couple of moving parts we'll need to get done first (like move Elm out of this repo)

**Comment by lloydstubber** [comment]
@ActuallyACat did you end up creating an issue for this?

**Comment by ActuallyACat** [comment]
@lloydstubber There's a (now closed) issue here: https://github.com/cultureamp/kaizen-design-system/issues/1729

Given the inconsistencies of where we distributable/compile Javascript, this issue reoccurs every couple of weeks/months. :/ Hoping to fix this properly with TS Project References, but until then we're going to need to patch these issues as we see them.

**Pull request merged**
