### PR TITLE
feat: include Kaizen link style in RTC and RTE

### PR DESCRIPTION
**Pull request by louiseliang**
# Keeping this PR Here to investigate strange hanging storybook pointing to the incorrect S3 bucket asset issue 

## Why

Please note that the PR is left as a debug PR for branch deployment issue:
image

More details in [thread](https://cultureamp.slack.com/archives/C0189KBPM4Y/p1666574718973359)

### CODE REVIEW

**Comment by louiseliang** [comment]
@mcwinter07 Could I close this PR or if still you need it for investigation?

**Comment by mcwinter07** [comment]
> @mcwinter07 Could I close this PR or if still you need it for investigation?

@louiseliang haven't had time to investigate yet, but if its getting in the way of your dev you can close this

**Comment by louiseliang** [comment]
> > @mcwinter07 Could I close this PR or if still you need it for investigation?
> 
> @louiseliang haven't had time to investigate yet, but if its getting in the way of your dev you can close this

no, just don't want to pollute your PR list :) happy to leave it

**Comment by gyfchong** [comment]
Closing as this fixed itself, let's revisit if it comes up again.

**Pull request closed without merging**
