### PR TITLE
feat: Put rebrand components behind soft feature flag

### PR DESCRIPTION
**Pull request by ActuallyACat**
# Objective
Introducing a rebrand flag in design tokens will allow consumers to accurately reflect the rebrand in their repositories (defaulting to false, set to true for any canary release of tokens). This now includes the non 1-to-1 changes in Kaizen, so they are not flagged as false positives when reviewed by the team. 

# Motivation and Context 
Swapping from the current palette to the rebrand palette gets us close to the end goal of the rebrand. However, there are quite a few situations in kaizen where we cannot swap the tokens 1 for 1, as these changes do not reflect the design vision. 

Reading: https://medium.com/eightshapes-llc/naming-tokens-in-design-systems-9e86c7444676

# Screenshots (if appropriate)
As an small example, this swaps all existing purples to the new purple scheme (note the input borders)
Screen Shot 2021-01-22 at 2 47 36 pm

This should instead look like this (with muted borders on inputs)
Screen Shot 2021-01-22 at 3 14 38 pm

# Checklist

**Marc's legend:**
✅ = reviewed and approved
🚧 = reviewed with changes
💀 = needs to die / be deprecated
🙈 = couldn't see / find the story
❓ = I have questions

- [x] avatar ✅
- [x] badge 🚧
- [x] button ✅
- [x] card ✅
- [x] checkbox-group ✅ 
- [x] collapsible ✅
- [x] divider ✅
- [x] dropdown 💀 
~~- [ ] dropdown-menu~~
- [x] empty-state 🚧
- [x] events (no change) 🙈 
- [x] filter-menu-button (no change) ❓ 
- [x] form 🙈 
- [ ] global-notification 🚧 
- [x] guidance-block 🚧
- [x] hero-card (no change, not in the UI Kit) 🚧
- [x] hero-panel (no change, not in the UI Kit) 🚧
- [ ] hierarchical-menu (not in the UI Kit)
- [ ] hierarchical-select (not in the UI Kit)
- [x] illustration (no change) ✅
- [ ] likert-scale-legacy
- [x] loading-placeholder ✅
- [x] loading-spinner 🚧
- [ ] menu
- [x] modal 🚧
- [x] page-layout
- [x] popover 🚧
- [x] radio 
- [x] radio-group
- [ ] search-box
- [x] select
- [ ] slider
- [x] split-button
- [x] table
- [x] tabs (no change)
- [ ] tag
- [x] tile
- [x] title-block-zen
- [ ] tooltip
- [ ] user-interactions
- [ ] vertical-progress-step
- [ ] well
- [ ] zen-navigation-bar
- [ ] component-library
- [ ] deprecated-component-library-helpers

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline? 
- Have Storybook stories been updated? 

**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask Design Systems team to review it to catch any issues.

### CODE REVIEW

**Comment by katsambarcus** [comment]
### **Avatars:**
**Default User** - the avatar is set to Purple 800 with 75% opacity. It looks like it was missed in the execution doc, but can we change the 75% opacity decision token to 70%, please? This will ensure we're maximising the contrast range of the new purple to the absolute threshold of legibility for AA compliance.

> The lightest percentage of opacity/alpha that can be applied to dark text (Purple 800) is 70%, before it fails contrast ratios. Primarily used to deemphasize text, such as metadata. Minimum contrast ratios 4.5:1 @ 16px.

**Comment by katsambarcus** [comment]
**### Badge**
**Dark vs Default (Kaizen Site Demo):** There is an inconsistency in the background color of these two stories. I'm not sure what the difference is between these two in terms of usage. Dark seems to be the anomaly, as we don't refer to a Dark badge in the UI Kit. The correct background color should be Ash 300, as defined on the Default Badge.

**Comment by ActuallyACat** [comment]
> Dark seems to be the anomaly, as we don't refer to a Dark badge in the UI Kit. The correct background color should be Ash 300, as defined on the Default Badge.

It _looks like_ it was introduced as a replacement for `reversed` - Not quite sure why. I'll chase up.

**Comment by katsambarcus** [comment]
### Button (Zen) (Elm)

**Default:** The click/focus state for this button needs the same background color as the hover state (Stone 200). Currently, it reverts back to white.

### Button (Zen) (React)

**For all Default style buttons in storybook (including Fixed Width, Hyperlink, Label + Icon etc):** The click/focus state for this button needs the same background color as the hover state (Stone 200). Currently, it reverts back to white.

**For all Default style, Working buttons in storybook (including Fixed Width, Hyperlink, Label + Icon etc)** The color of the spinner is using the incorrect color. Moving part of the spinner = Purple 800 with static ring (lighter shade) = Slate 700 (20%)

**For all Destructive, Working buttons:** The color of the spinner is incorrect. Moving part of the spinner = White 100 with static ring (lighter shade) = White 100 (20%)

**For all Primary, Working buttons:** The color of the spinner is incorrect. Moving part of the spinner = White 100 with static ring (lighter shade) = White 100 (20%)

**For all Secondary, Working buttons:** The color of the spinner is incorrect. Moving part of the spinner = Cluny 500 with static ring (lighter shade) = Cluny 500 (20%)

image

ℹ️  This is a relatively new decision, so apologies. The image above shows the varying types of spinner colors to work harmoniously with the different color buttons. The 'Default' spinner should primarily be used for visualising loading outside of a button.

** ⚠️ Note: the colors in this image are taken from the Zen UI Kit - I don't have a visual from the new themed UI Kit yet**

@ActuallyACat it might be worthwhile if we pair on these to make sure there's not confusion

---

### Non-color specific issues:

**[Overflowing, text form button](https://dev.cultureamp.design/ally/decision-tokens/storybook/?path=/story/button-zen-react--overflowing-text-form-test-case) is the wrong size.** All buttons should be 48px in height.

**Comment by katsambarcus** [comment]
### Card (Elm)
**Default:** Shadow on card is currently using Wisteria 800. Shadows are one of the few places in our product where we use black . The correct color value for the shadow should be #000000 with 9% opacity/alpha.

### Card (React)
Same as above applies to all of the React stories / components.

image

**Comment by katsambarcus** [comment]
### Collapsible (React) (not in UI Kit)

- Remove outside border completely
- Change border-radius to 7px
- Dividers between sections should use the Content Divider component (Slate 700 (10%))
- Selected container with background color on header: Change from Purple 100 to Stone 200. If Stone 200 doesn't work, use Ash 300
- Change shadow to #000000 9% opacity/alpha <-- @ActuallyACat re shadows. Do we have these defined as a token?

**Comment by katsambarcus** [comment]
### Divider (Elm)

**Canvas:** Change color from #524e56 (20%) to Slate 700 (10%)
**Content:** Change color from #524e56 (10%) to Slate 700 (10%)

**Canvas (Reversed):** No change
**Content (Reversed):** No change

### Divider (React)

**Canvas:** Change color from #524e56 (20%) to Slate 700 (10%)
**Content:** Change color from #524e56 (10%) to Slate 700 (10%)

**Canvas (Reversed):** No change
**Content (Reversed):** No change

**Comment by katsambarcus** [comment]
### Dropdown (React)

All of the stories related to Dropdown are very old and should probably be deprecated. I believe [Menu](https://www.figma.com/file/GMxm8rvDCbj0Xw3TQWBZ8b/?node-id=6262%3A0) is the visual source of truth for components with dropdowns.

**Comment by katsambarcus** [comment]
### Empty States (Elm)

All heading sizes for React components are incorrect. Currently using previous H3 styling (22px). Needs to change to new H3 heading typestyle (20px)

### Empty States (React)

All heading sizes for React components are incorrect. Currently using previous H2 styling (30px). Needs to change to new H3 heading typestyle (20px)

**Comment by katsambarcus** [comment]
Global Notification

This component hasn't been reviewed yet (in fact, it wasn't in the list, so I added it).

I've realised I'd neglected to mention a few changes in the Execution Doc (which I've now updated). See below for changes required:

**Informative** 
background-color: Cluny 300 → Blue 200

**Positive**
background-color: Seedling 200 → Green 200

**Negative** 
background-color: Coral 300 → Red 200

**Cautionary**
background-color: Yuzu 400 → Yellow 200

**Dismissible**
close-icon: Wisteria 700 → Purple 800 (70%)

⚠️ Also worth noting that the way we visualise the icons on these global notifications has evolved, and will need to be updated in code (see below for visuals) or [reference the sticker sheet](https://www.figma.com/file/vblsTm2rut20C0y3x4Tg6o/?node-id=1929%3A21283)

image

**Comment by katsambarcus** [comment]
### Filter Menu Button

❓ @ActuallyACat, I wonder if this story should be 1 piece of the larger Filter Bar pattern / story? I suspect the only place we'll use these buttons is strictly within the Filter Bar pattern and it would make sense to keep all the parts of the pattern under a single story to minimise naming issues and discoverability. Thoughts?

**Comment by ActuallyACat** [comment]
@katsambarcus 
> Change shadow to #000000 9% opacity/alpha <-- @ActuallyACat re shadows. Do we have these defined as a token?

The shadow tokens in Kaizen use wisteria:
```
$kz-shadow-small-box-shadow: 0 0 6px rgba(53, 55, 74, 0.09);
$kz-shadow-large-box-shadow: 0 0 12px rgba(53, 55, 74, 0.19);
```

**Comment by katsambarcus** [comment]
### Guidance Block

This is more of a UX consistency issue, but the close button (dismiss) should use the icon button so it's similar to how our modals and other dismissible components work. Not a pressing matter, but if it's simple enough to switch out, that would be fab!

image

**Comment by katsambarcus** [comment]
### Hero Cards

One small change. Change the Purple from 700 to 600

image

**Comment by katsambarcus** [comment]
### Hero Panel

Same deal as the Guidance Block. It'd be nice to make use of the Icon Button for dismissible patterns like this.

image

**Comment by katsambarcus** [comment]
### Loading Spinner

Both big and small spinners are using Wisteria 700 with 20% opacity for the background circle. Change this to Slate 700 with 10% opacity. The green part should be Green 400 (but I couldn't find a way with the inspector to confirm it)

**Comment by katsambarcus** [comment]
Modal (React & Elm)

@ActuallyACat The background colors look good, but there are a couple of other things to tweak:

1. The close icons on these modals are currently white (because the backgrounds used to be darker). Can we update these to use the Default Icon Button? Refer to https://www.figma.com/file/GMxm8rvDCbj0Xw3TQWBZ8b/?node-id=1929%3A35439 for positioning.

2. The heading typestyle is NQR. It should be referencing the H2 typestyle. But it's way too big (36px (Old H1) instead of 28px) and the weight feels a little too light too. Can we check the bold weighting. 

⚠️ **Suggestion: Before changing at the modal level, could we confirm that all the type updates have been made, please?**

image

**Comment by katsambarcus** [comment]
### Popover

Colors look fine 👍 

The positioning of the header feels a bit off. Too close to the top of the popover and too distant from the body copy. Refer to the UI Kit for correct distances.

Also, wondering if it also makes sense to introduce the Icon Button for the dismissible close icon?

image

**Pull request closed without merging**
